# Generated by Django 3.1 on 2023-12-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_members', models.PositiveIntegerField()),
                ('max_members', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.CharField(max_length=5)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Packages.package')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
