# Generated by Django 3.1 on 2023-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0002_auto_20231203_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(upload_to='package_images/'),
        ),
    ]
