# Generated by Django 3.1 on 2023-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0003_auto_20231209_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image2',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='image3',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='image4',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(null=True, upload_to='package_images/'),
        ),
    ]
