# Generated by Django 3.1 on 2023-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0005_package_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
