# Generated by Django 3.1 on 2023-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0006_auto_20231210_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
