# Generated by Django 3.1 on 2023-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0008_auto_20231211_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_request', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
