# Generated by Django 3.1 on 2023-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0009_auto_20231220_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='date',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='time',
            field=models.TimeField(max_length=255, null=True),
        ),
    ]
