# Generated by Django 3.1 on 2023-12-13 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0008_auto_20231211_0946'),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Packages.package'),
        ),
    ]
