# Generated by Django 3.1 on 2023-12-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_review_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='username',
        ),
    ]
